### ISSUE TITLE
Delete Cargo.lock

### ISSUE THREAD

**Issue by mrMiiao** [artegoser/ONLang#3]
`Cargo.lock` is a file generated in time of build and is not a part of the project.

**Comment by artegoser** [comment]
Fixed in: 8fef9f68e258a476541118fb0cdcabe1c2eb1ea3

**Comment by SDesya74** [comment]
Reasons NOT to delete .lock files:

https://stackoverflow.com/questions/48524417/should-the-package-lock-json-file-be-added-to-gitignore#48524475

https://stackoverflow.com/questions/43667176/what-files-in-a-cargo-project-should-be-in-my-gitignore#43667316

**Comment by artegoser** [comment]
Hm...

**Comment by SDesya74** [comment]
Removing .lock files is a very bad idea, because without them the dependencies in the cloned repository will not match the original ones and you can get bugs due to mismatch of dependency versions. 

Given that you have not strict dependencies in the Cargo.toml file, this can play a trick on you.

**Comment by mrMiiao** [comment]
Reasons to delete `Cargo.lock`:
1. This crate cannot be used as a dependency (it doesn't even have a `lib.rs`);
2. Developer specified most of the versions in `Cargo.toml and` is gonna specify last ones.

**Comment by SDesya74** [comment]
> 1. This crate cannot be used as a dependency (it doesn't even have a `lib.rs`);

What does that have to do with it? This project itself uses external dependencies that won't match when someone else clones the repository. This is not an argument at all.

> 2. Developer specified most of the versions in `Cargo.toml and` is gonna specify last ones.

The meaning of the lock file is not to specify dependencies manually, but to specify them using SemVer. If you remove the lock file, then all automated work will turn into manual work, where you will have to independently specify specific versions of libraries up to a commit. It's completely pointless.

**Comment by SDesya74** [comment]
> 1. This crate cannot be used as a dependency (it doesn't even have a `lib.rs`);

And here is this? This project itself uses external dependencies that won't match when someone else clones the repository. This is not an argument at all.

> 2. Developer specified most of the versions in `Cargo.toml and` is gonna specify last ones.

The meaning of the lock file is not to specify specific dependencies manually, but to specify them using SemVer. If you remove the lock file, then all automated work will turn into manual work, where you will have to independently specify specific versions of libraries up to a commit. It's completely pointless.

**Comment by mrMiiao** [comment]
> is not an argument at all.

Typical lol. `is not an argument at all` is not an argument at all.

> uses external dependencies

Don't rust-lang/cargo, rust-lang/libc and many other crates use external dependencies too?

> The meaning of the lock file is not to specify specific dependencies manually, but to specify them using SemVer. If you remove the lock file, then all automated work will turn into manual work, where you will have to independently specify specific versions of libraries up to a commit. It's completely pointless.

The most pointless thing @artegoser can do now is to carry useless file when he can just add some more digits to the cargo manifest)

**Comment by artegoser** [comment]
What about this - https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

**Comment by SDesya74** [comment]
> The most pointless thing @artegoser can do now is to carry useless file when he can just add some more digits to the cargo manifest)

Using a lock file costs nothing. Manually writing versions of ALL dependencies, specifying them with commit and hash accuracy (to achieve lock file accuracy) is much more difficult and will have to be done by hand. 

I don’t consider the rest of the statements to be a worthy argument, since the mentioned projects say why they removed the lock files and these reasons do not fit this project.

**Comment by mrMiiao** [comment]
> is much more difficult

If you find typing several digits difficult, maybe programming is not for you. Just consider reading some recomendations from Cargo FAQ which tells us that crates `should always specify the range that they do work with, even if it’s something as general as “every 1.x.y version”`.

> I don’t consider the rest of the statements to be a worthy argument, since the mentioned projects say why they removed the lock files and these reasons do not fit this project.

Then just stop arguing with me.

Sorry if my messages look rude, i didn't mean injuring you.
